name: Deploy

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
      - uses: bahmutov/npm-install@v1
        with:
          working-directory: backend
      - name: Build frontend
        run: npm run build
      - name: Build backend
        run: npm run build
        working-directory: backend
      - run: |
          mkdir artifacts
          mv dist artifacts/frontend
          mv backend/dist artifacts/backend
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: ./artifacts

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: github.ref == 'refs/heads/main' && github.repository_owner == 'kast-lang'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: artifacts
          path: ./artifacts
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: artifacts/frontend
      - name: Copy files to VPS
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.BACKEND_HOST }}
          username: ${{ secrets.BACKEND_USER }}
          key: ${{ secrets.BACKEND_SSH_KEY }}
          source: 'artifacts/backend/server.js'
          target: '/home/${{ secrets.BACKEND_USER }}/playground-backend'
          strip_components: 2
      - name: Restart backend with systemd --user
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.BACKEND_HOST }}
          username: ${{ secrets.BACKEND_USER }}
          key: ${{ secrets.BACKEND_SSH_KEY }}
          script: |
            cd /home/${{ secrets.BACKEND_USER }}/playground-backend
            # Restart systemd user service
            export XDG_RUNTIME_DIR=/run/user/$(id -u)
            systemctl --user daemon-reload
            systemctl --user restart kast-playground-backend
